version: '3.8'

services:
  web:
    build: .
    container_name: pokeapi-web
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=backend/main.py
      - FLASK_ENV=development
      - DB_HOST=pgsql
      - DB_PORT=5433
      - DB_USER=pokemon
      - DB_PASSWORD=${PGSQL_ADMIN_PASS}
      - DB_NAME=pokeapi
    depends_on:
      - pgsql
    volumes:
      - .:/app
    networks:
      - pokeapi-network

  pgsql:
    container_name: pgsql
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${PGSQL_ADMIN_PASS}
      - POSTGRES_USER=pokemon
      - POSTGRES_DB=pokeapi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - pokeapi-network

networks:
  pokeapi-network:
    driver: bridge

volumes:
  postgres_data: