"""create pokemon table

Revision ID: 513a78645f17
Revises: 
Create Date: 2025-05-08 11:37:09.201680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513a78645f17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('google_sso_id', sa.String(length=100), nullable=True),
    sa.Column('facebook_sso_id', sa.String(length=100), nullable=True),
    sa.Column('linkedin_sso_id', sa.String(length=100), nullable=True),
    sa.Column('apple_sso_id', sa.String(length=100), nullable=True),
    sa.Column('microsoft_sso_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('login_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('disabled_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_user_created_by_user_id'),
    sa.ForeignKeyConstraint(['disabled_by'], ['user.id'], name='fk_user_disabled_by_user_id'),
    sa.ForeignKeyConstraint(['modified_by'], ['user.id'], name='fk_user_modified_by_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uq_apple', 'user', ['apple_sso_id'], unique=True, mssql_where='apple_sso_id IS NOT NULL')
    op.create_index('ix_uq_facebook', 'user', ['facebook_sso_id'], unique=True, mssql_where='facebook_sso_id IS NOT NULL')
    op.create_index('ix_uq_google', 'user', ['google_sso_id'], unique=True, mssql_where='google_sso_id IS NOT NULL')
    op.create_index('ix_uq_linkedin', 'user', ['linkedin_sso_id'], unique=True, mssql_where='linkedin_sso_id IS NOT NULL')
    op.create_index('ix_uq_microsoft', 'user', ['microsoft_sso_id'], unique=True, mssql_where='microsoft_sso_id IS NOT NULL')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('generation', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('disabled_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_pokemon_created_by_user_id'),
    sa.ForeignKeyConstraint(['disabled_by'], ['user.id'], name='fk_pokemon_disabled_by_user_id'),
    sa.ForeignKeyConstraint(['modified_by'], ['user.id'], name='fk_pokemon_modified_by_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('infoPokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon_name', sa.String(length=80), nullable=False),
    sa.Column('move', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('disabled_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_infoPokemon_created_by_user_id'),
    sa.ForeignKeyConstraint(['disabled_by'], ['user.id'], name='fk_infoPokemon_disabled_by_user_id'),
    sa.ForeignKeyConstraint(['modified_by'], ['user.id'], name='fk_infoPokemon_modified_by_user_id'),
    sa.ForeignKeyConstraint(['pokemon_name'], ['pokemon.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('infoPokemon')
    op.drop_table('pokemon')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index('ix_uq_microsoft', table_name='user', mssql_where='microsoft_sso_id IS NOT NULL')
    op.drop_index('ix_uq_linkedin', table_name='user', mssql_where='linkedin_sso_id IS NOT NULL')
    op.drop_index('ix_uq_google', table_name='user', mssql_where='google_sso_id IS NOT NULL')
    op.drop_index('ix_uq_facebook', table_name='user', mssql_where='facebook_sso_id IS NOT NULL')
    op.drop_index('ix_uq_apple', table_name='user', mssql_where='apple_sso_id IS NOT NULL')
    op.drop_table('user')
    # ### end Alembic commands ###
